services:
  minecraft:
    image: ${MINECRAFT_IMAGE}
    stdin_open: true
    tty: true
    environment:
      - EULA=TRUE
    ports:
      - 25565:25565/tcp
    volumes:
      - ${MINECRAFT_DATA}:/data
    restart: always
